# Generated by Django 3.0.2 on 2020-01-02 17:06

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa stanowiska')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('PESEL', models.IntegerField(verbose_name='PESEL')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel')),
            ],
            options={
                'verbose_name': 'worker',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPaid', models.BooleanField(verbose_name='Płatny')),
                ('dateOfStart', models.DateField(verbose_name='Początek')),
                ('dateOfEnd', models.DateField(verbose_name='Koniec')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPaid', models.BooleanField(verbose_name='Płatny')),
                ('employmentDate', models.DateField(verbose_name='Data zatrudnienia')),
                ('endOfEmploymentDate', models.DateField(blank=True, verbose_name='Data zakończenia zatrudnienia')),
                ('type', models.CharField(
                    choices=[('FT', 'W pełnym wymiarze godzin'), ('PT', 'W niepełnym wymiarze godzin'),
                             ('T', 'Okres próbny')], max_length=2, verbose_name='Type')),
                ('description', models.TextField(blank=True, max_length=150, verbose_name='Opis')),
                ('hourWage', models.FloatField(verbose_name='Stawka godzinowa')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Position')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='worker.Worker')),
            ],
        ),
    ]
