# Generated by Django 3.0.2 on 2020-01-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, default=0, verbose_name='Kwota')),
                ('paymentMethod', models.CharField(choices=[('C', 'Karta'), ('CD', 'Gotówka')], max_length=2, verbose_name='Metoda płatności')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('notes', models.TextField(blank=True, max_length=150, verbose_name='Notatki')),
                ('isParkingSpotNeeded', models.BooleanField(verbose_name='Miejsce parkingowe')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Client')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.Receipt')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Room')),
            ],
        ),
    ]
